FROM python:latest

WORKDIR /app

COPY payments/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY payments/app.py ./app.py
COPY payments/payments.sql ./payments.sql
COPY key.txt ./key.txt  

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]