FROM python:latest

WORKDIR /app

COPY reservations/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY reservations/app.py ./app.py
COPY reservations/reservations.sql ./reservations.sql
COPY key.txt ./key.txt  

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]