FROM python:latest

WORKDIR /app

COPY availability/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY availability/app.py ./app.py
COPY availability/availability.sql ./availability.sql
COPY key.txt ./key.txt  

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]