FROM python:latest

WORKDIR /app

COPY users/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY users/app.py ./app.py
COPY users/user.sql ./user.sql
COPY key.txt ./key.txt  

ENV FLASK_APP=app.py

EXPOSE 5000

CMD ["python", "app.py"]